---
music_container_mount: /srv/music
music_gid: 1500
music_stack_dir: /opt/music-stack
music_app_image: ""
music_slskd_image: slskd/slskd:0.26.0
music_slskd_web_port: 5030
music_slskd_listen_port: 2235
