apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: verdaccio
  namespace: tools
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - npm.{{ .Values.global.homeDomain }}
  rules:
    - host: npm.{{ .Values.global.homeDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: verdaccio
                port:
                  number: 4873