postgresql_password: ENC[AES256_GCM,data:a06aBHUxid0dDoSOZlMzOM7bAvqrqDSoGTWO0ExVNKU=,iv:fdoAE/V2e0tfKEKLKW8+rMJwKU/hgelkCxdo46lR6ZU=,tag:6VCrx8dJG7YyV5attV3FWg==,type:str]
forgejo_secret_key: ENC[AES256_GCM,data:CbXyXm97IyemgGMYugEeR7fJn2CVCWYbFc8oSwS07HOhnDwIPCjWvPqpEA==,iv:w8NlRR2MFHQlR6PW2nCQ+SOZsBstjL/N8GSHfaHs0Cw=,tag:bb3UUwjgZ4ZlrYzZE0i7QQ==,type:str]
forgejo_internal_token: ENC[AES256_GCM,data:fs1el1sp9yebvZCLRHIrvwG1rNt6E6uPJ34u7HxoQa3PTw5vMAPEsYEBXaYJ+g36f3mGOBd3NJrGzhsJoOneT4nw7GB4BSN/VwqU0UKzhhIG3vINWF8WMIcRWZfvjQtPGNf07dxbtInb,iv:o/TeDwI986ifYLgtIHSnJsU8JFLedaLK/MglRqPjWnM=,tag:fNUCIMgY/yCemdKQ+rQ//w==,type:str]
forgejo_admin_password: ENC[AES256_GCM,data:Eh8Qx9ppZllMUpXZwF1FidzRndsgRws07531n8108tk=,iv:RfJMNVuPUmBJ2F9h+f1qDwjkspXVTxzTr17zWU6E1aw=,tag:D3BSMaYZaIKQzzFhjP3qjQ==,type:str]
forgejo_jwt_secret: ENC[AES256_GCM,data:yiPUZEBGG4dP6n/On4ngxthq2j1SuIDGDC26GW8E4jtqaqtuWzJ4qCA7eQ==,iv:HfCjiUuZA6uweKt98uB8vSEPSTqg0maZ/CbMoSEL34A=,tag:Qkrkuk8GT9qnpE/Z/e5t8w==,type:str]
forgejo_lfs_jwt_secret: ENC[AES256_GCM,data:UEENOYQIDSjirwFizWzi0IiU8RLTghoi6DyjC4WNDziDNnKcSlxi0Phlcw==,iv:v46ThJLuS4QlEuwKY44wKW1HLDdEifqEA5TBji3mkFg=,tag:9g6cR33hBhHtpYzb4TZoKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVGxxU2V0dnRjdjEwSUgw
            UWJpaFBQYUVHMVF3ZFpoUU9uY0EwK05CeVhFCjR5amZJTDJ2M0JGMlo2cWE0YkxD
            WG9qcjlsTCtLTDdtanh4SEVrY05jdUkKLS0tIHZkaDE3dEtQNS9ySk04S1N3VFdI
            MHFqblFEenhrbFVoYjc0THZHalFKcncKiDo2otOaihr904Fqw9P/p2j2yLJAL5l5
            ppD6/T6ku4rlZHBZR32gEPX1IcsxvnelsEEKOpxDKk8wof41lRQpPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gt9v3qjej3vuykjydqv9amhsjucanjwwtt4w8fkf5thyssrdeuus5ke3rx
    lastmodified: "2026-07-26T10:12:05Z"
    mac: ENC[AES256_GCM,data:MAxiqKQ6qeJ+QT4xy0AexpMJYIniayeFsxbSLhFi9up5k9JlIhwZw1yPCCDjV65tsvexHmTiiJo5s7vpfFkwxUOLsaeLBK2f7d/e+L30MrNqqwEdxo7kgfbWtbems9KvEp/WSbV1tcpkUr1JfIZnaqHtJXQ9nB7GykzEGGHoy1E=,iv:1XiwWBtNSKrvlbRHyay/mWlHJM5sjuRO3aSBeJKXcNI=,tag:8KMK99+X26bTw24KmUOdPQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
