music_smb_password: ENC[AES256_GCM,data:Ddd67fQ03Fllu0rb8D82bhe070B6Re3m,iv:VP4b6dF78jXETKhi2w1EobQs1MqfZk4QvxPISflifK8=,tag:TaeNKiP6/VjW4sHYk5+/pg==,type:str]
syncthing_gui_password: ENC[AES256_GCM,data:er1Qi4Hu/5Z7V0QgkgdbXNdPq2K+4NmR,iv:Mo02leEf2gqTAbzbKOKN2DwXo3TrHv+xmbxx6xJcdOI=,tag:3H8wQy2z85HGeOyzMMLGiA==,type:str]
slskd_web_username: ENC[AES256_GCM,data:xnW5AdI=,iv:v9SzzHkD96GYhQTNP2FdiQ0jTv2iVb7sayzCYN79t+8=,tag:oTS4hYCPf8s2xrf3Kte4hw==,type:str]
slskd_web_password: ENC[AES256_GCM,data:34Grzq3Lai+Ox1gD5u2nJw4KMWxyMelG,iv:ul1SBfehj4DTJ3gXOqetNjeItX8dDkoaUeZWE3Eo3vQ=,tag:dm40Xe1WTdo9eHa3eLqzfA==,type:str]
museek_slskd_api_key: ENC[AES256_GCM,data:ENV8yr3hfDgVG/+3JVm7KXuzDp9Gn4hSGgwMvFMFkXx2BtxL509vnxLla3Tjrf2XHykkXk/05rN/yoXfr+lYOg==,iv:3TQhrWDx6BDB2v2h+XlbMp6bqPwB/Daq0GLg5WukunA=,tag:+/Bn4vrwrqCkFvk8EQd5Jw==,type:str]
museek_api_token: ENC[AES256_GCM,data:7wZyb1hImpmq6/2m5lQf0t9wUBFccVzwYNEPG7lKgY+TQqC3Ayld2khsN7z6xnJI2KL1uD8XtEtqI90M284j9w==,iv:+erpdAu0BovPZuc1GhU9aiqPqA/vNr8la5RfTE/vTnc=,tag:cdhoobm+wZik5K+S0X+pZg==,type:str]
museek_spotify_client_id: ENC[AES256_GCM,data:3XZcrEYEG0kPrJG9i41xZB3BA3tLosP51AFvjl3sVBE=,iv:ZPSjTekpk1kAKaqZ0hWFbcysxtv/UzSMNcyjztyaTqE=,tag:X8R026U+R3xN+whwp/AinQ==,type:str]
museek_spotify_client_secret: ENC[AES256_GCM,data:cXGFBHdLfXwTmW7MJ32tsuZVcMO8vwR2+zZKLmXrsgM=,iv:MXl5vW+q6Sp23X4i9XBGMBvegBP29W8VGKWnJlnGcnw=,tag:RI7YX5Jx1dEPx67BWAQaLQ==,type:str]
slskd_soulseek_username: ENC[AES256_GCM,data:cSx+1rK5wB8PIHe0mMw8hH8=,iv:YqQnkjqQYXoWpiLPbFoLTlqs+fe2PBHN0vwUFX/GHHg=,tag:H9MXio7xwBsfi6VMXQPrew==,type:str]
slskd_soulseek_password: ENC[AES256_GCM,data:nA/cKj2q2S/Dv0vdgLxGWazgUI9X2LXh,iv:ckNsTZq1bgfYiWllETQ9/ksU8qNU8IS+LiyAjYfYAVU=,tag:/RfJRH0V/gSLcExz0m4usw==,type:str]
museek_discord_token: ENC[AES256_GCM,data:8WtrqvkZErVZzu/4kDxkyDelAnd4x876+/IGiIOu2baN4RQODcsS07mryfLSXQhffqtlL5j1RgDD8bxSIjNT3nfYH9FAJBQA,iv:xVXNq2yUmeBSMIDFgjNbZxReH70iqXPFnMWeqRi4PIY=,tag:3PswMH9TlBKWfZmjWOz4+A==,type:str]
museek_discord_guild_id: ENC[AES256_GCM,data:txgvJj4CAaQsjJomZgrBMsm7mA==,iv:P6k0hJvV20s2ap/0WwFnn9JCSe16vYScz0FhPFpyB24=,tag:fH02B31CCzGXPluSaV4taQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeEVGKzVJNTYrWEh0eks5
            dmhnY2hET1Q1U0dRUGRENTEvQlQreHE3M1JnCjA2aWhyN3pUb0M2bVI5bE93R0l1
            U3VoeG1oSTNJTFBGd2MveFJTQ0taMTgKLS0tIG9jZEJqbGF1dUY5MFFOZFFEdFY0
            anFSRk9LcWYxbVFLZmE1WGZndzlhcXMKOanFVySFhB+LdljIj82f/pVr6CLBWfOO
            wy1O/JWTETKk2gzKxpkqzminkCQGIXDFuFfP4Dkl2ohXnQi58iiqtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gt9v3qjej3vuykjydqv9amhsjucanjwwtt4w8fkf5thyssrdeuus5ke3rx
    lastmodified: "2026-07-26T11:42:57Z"
    mac: ENC[AES256_GCM,data:TNRLIdvazE2KGQFa0QgH8BKQNYVihlukrFY4E925zw5ZRlPqf/Vi/tyAiHcSYofoCe+ORdXS1/djS8YuH2PgLwKnfbS1StWfaoC/UD63eX5iOffxjjeBdD5uQs6qvwMp7TaRPJNE3m0QcCkrxiwJF7f069Sf0y2CNbU7Oe7H0Cs=,iv:i/PlEUtYbikozkoSTmHHZdk1kbxNNp6Oh1kOUhl47Pc=,tag:sQ08YRXeJ5WjSREWhtjnTQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
