---
music_container_mount: /srv/music
music_gid: 1500
music_share_name: music
music_smb_user: phill
music_stack_dir: /opt/music-stack
music_app_image: ""
music_slskd_listen_port: 2235
music_syncthing_gui_port: 8384
music_syncthing_user: syncthing
music_museek_port: 8080
music_museek_match_threshold: "0.6"
museek_musicbrainz_contact: ""
