---
ansible_user: root

terraform_user: terraform@pve
terraform_role: Terraform
terraform_token_id: provider
terraform_role_privs:
  - Datastore.Allocate
  - Datastore.AllocateSpace
  - Datastore.AllocateTemplate
  - Datastore.Audit
  - Pool.Allocate
  - Sys.Audit
  - Sys.Console
  - Sys.Modify
  - VM.Allocate
  - VM.Audit
  - VM.Clone
  - VM.Config.CDROM
  - VM.Config.Cloudinit
  - VM.Config.CPU
  - VM.Config.Disk
  - VM.Config.HWType
  - VM.Config.Memory
  - VM.Config.Network
  - VM.Config.Options
  - VM.Migrate
  - VM.PowerMgmt
  - SDN.Use

pve_signing_key: /usr/share/keyrings/proxmox-archive-keyring.gpg
pve_suite: trixie
pve_repositories:
  - name: pve-enterprise
    types: [deb]
    uris: https://enterprise.proxmox.com/debian/pve
    components: [pve-enterprise]
    enabled: false
  - name: pve-no-subscription
    types: [deb]
    uris: http://download.proxmox.com/debian/pve
    components: [pve-no-subscription]
    enabled: true
  - name: ceph
    types: [deb]
    uris: http://download.proxmox.com/debian/ceph-squid
    components: [no-subscription]
    enabled: true

root_authorized_keys:
  - "REPLACE_WITH_ssh-ed25519_PUBLIC_KEY_CONTENTS"
