---
zot_version: v2.1.18
zot_sha256: "a359a0af159db6758b24f8e26d6a244aae95caf3ff382c462875f42d9e082898"
zot_upstreams:
  - host: ghcr.io
    url: https://ghcr.io
  - host: quay.io
    url: https://quay.io
  - host: registry.k8s.io
    url: https://registry.k8s.io
