---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-ddns
  namespace: cloudflare
spec:
  encryptedData:
    api-token: AgCz0nyOMMvRETWvcKFipC/Q4so9QRQ7iYaR0XDqI23k4jJaflE6NwOoGA+0APKZj+MeZqfKpCnZHP0DoZOq8QfBAV3W7Zf7WcieNCmgfPfGkdjIOQi3j2k4DR3/oEa7nwV23OfXIAk63aR5TyILwotkQdVpSONHt/YvAOrjnS06VnE9+xtdpdaYUGA4RysNF/jjDrhSGefUNGEFVy2WtDbUGTo7wEW7FQ4t/dMolsixHvTosnezXasYe00IPC/wToBRyMFJiUeG57AJlmgA8VwTYO4f/U++lURW/HdkSdmXd6K63LIwyyKVL5JTPmofv7xMSVQpRtc5UTSrECxM8kOKdCuqbpkxB+gazwDJPxAokE0hchHCr+NNBlP9a7iP9IhJA5WFY0TUGF6P3RpjKvaltmf4fWId5zgNSjLkBE/DlxGKpGw13gz/pMAFvd+5R+QOYZ1m6fkChRoZ6ghlPe0Ndr5wcCDRT1rtCvln8IfLCEU2qzjNnLybeQRR3QmgI91JLKgRfPqrnBCmaV7HKSUjqNY4Ys6jq4IwpsXgnsTeMw49WlIkzfF5D6b21/w3HLSkL7abNu4ZLzWDle/hu0za1FpiH9fTDxwRxA/MMVeCXzbQIAr7vUse3XFqdK9SIhv7s6WO4thvzzEBmhGsPOo+hmhqYymT8IZmVGIZcKsVf3FuZWoH822p56hUVNnK6MGBhrxVP4Qcwo6YrROUD2fxBS+6vjyLVmSumX1NA32BuwwV4nzNxoV7
  template:
    metadata:
      name: cloudflare-ddns
      namespace: cloudflare
