---
- name: Install headscale
  ansible.builtin.import_tasks: install.yaml
  tags: [install, headscale]

- name: Configure headscale
  ansible.builtin.import_tasks: config.yaml
  tags: [config, headscale]
