---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: synapse
  namespace: comms
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`matrix.{{ .Values.global.hobbyDomain }}`) && (PathPrefix(`/_matrix/client/v3/login`) || PathPrefix(`/_matrix/client/v3/logout`) || PathPrefix(`/_matrix/client/v3/refresh`))
      kind: Rule
      priority: 110
      services:
        - name: mas
          port: 8080
    - match: Host(`matrix.{{ .Values.global.hobbyDomain }}`)
      kind: Rule
      services:
        - name: synapse
          port: 8008
  tls:
    secretName: hobby-wildcard-tls
