---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headplane-secrets
  namespace: headscale
spec:
  encryptedData:
    api-key: AgBr/sSoDpTPWJNYKuTsRbWNfLGNVvdEWKIqPkCfhCbaa2ttjoJXrCtdI49QryCU3odhP+E1hTQv3mYg2N1CZWr5S+QdqxVWndm/+0zw6dObJqC7vtdGbGhpFMUCIpEYsMpW0y1YEGKUc0cNw+TUcARteUmIml3BUEOAZIQ56+K3tssFYgMXXsj2zUPX4I0TjeKMS6l55aMTZSgZi6487qKMbMZ1ClhHN4D0aO4KeWBgawY9klwLgOeNqruswux+EHQGI/uJQXctSaFxVrkenIkXwt3ZAHg3AEhbqj67HzCi26MH2xCjrpU8PFAuRStusfRODNz0iJ0pHmX8SOmXgAZspD1UN6Ex96Wdw8vBTwvIIFMpx79/2/qsragnJlug8pz44sxly9ynj5lLJ8PMUz0rRGjP74gq4DScJz1i9EAaZ8IxncVOGii+IY4jxUZEDZvglZUAg7FxodbIOJSoeEP3mLyeOm2exDgLwB3Ue9nGt5VBVIb+xC+uDnj6Ezfm7Y9YIqRB48BAb9TSO4DccHCM7t3ikYgWqAn907uvxZ5CZzgzgf9hmP41AIUg4i98pz2EcXmcCkJD+KUIifcemA6LsFQD7jKpsoO7IeUg12XUGJCQ4mQe+zI2kPRSOv0rsXS1gc0uumK0BAmclHor3FZiv/xcUEMVbsQVb0iuZhTXJJfNipAzF3O1ob55jgfYWYprS/kkbth7yeuo1qfv++uOjuTTVyWAVgRwwtqH66QNNExMYhft47F3mohan75LrB3Yq6S7JqU=
    cookie-secret: AgAMRR6iNU8sXFmqdgd1+jCBgWbEl0Kdwlf+hY6PhRX/vUaEhiE8ObrnVGoPW6knZXY1HeVeFncrlcRIx/Wazo9jeEDcSfE8YvVQkEoeZl50rJ5mRcB43KS0IfVG+d50wXv0kEWjnCxsvYKYT+JsOR/dPUaWpf9n0ClvQ2vz86P5NEsact+JL+BxpqgwoA0W8gDzvxqQiwgpYJfcWcdmB73zoXAhR1lbpsy4YVYCJw7adWzcQdZCWZDoWN+5EurlAH3BN6VUUDaCgo2fXdEZiVaffsQ5WD33QB20wUH09c+EVpV1HeL977lrjL1ua4XWx3wei/UNjCv/dioIKPQdbU/IX8BFz437vPYNIwUHj8cqnvERiWkMENZnnbjpokhmUxGkvlyftW8+CSrq88Ngoac9kMjCC44nlbWe4D2k218n+rKR53vb29Wzi8grzJmHzz1t3mSJBP9pPDy8XU2uKhjBQ3dV6WAf1fJF2PBa8dIolqlUuN5R0iAhzosqOtms5KNDbBNPPFabsqt2pnKVkDwpzRIVhMvkIz8THq5swsPyBlqOiDAS0W1BPJCqW6dOLm4Y6EsTcCNeNCZvwKVIqJvx1z4RCIew+7COJlpNPtw/qUIwZsEAbTEk5Mk2+6cKJs7mEUOUTH4zK9aVpthzmYnlQ1acu5d6aG5+GPJ/9U4Gv/SGx4eOJW7tILC/jIVvUYnnn0vdHm59lanocGeXjJzA3EMcsizI0kPjXNGmb4rmPjXZalQO0mChWEGXRQ==
  template:
    metadata:
      name: headplane-secrets
      namespace: headscale
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: headscale-oidc
  namespace: headscale
spec:
  encryptedData:
    client-secret: AgB5qjfe04vcuhd0jy/YINZbVvBJPjoPQE8wftZqzriVfE9jimovgEqWNTsXLcrXgMtfgcAIILbQaSjGPfTFB/ntxjLV98N6ZqGXmSY+3iV+5tyfPOEFG7XKFGKBMVXlNJALFLuCLdwYAL4JNY6WNto3mo2XGUlwVUBT/B0ORHxIJgFcO9dTEpd9V6JTXhgwyk/cP20qXJRBYWOdhJyN5eGoR+Y1vziIYvvO87W4DuiF/iB+B1hRLRYgUrI+AmlUIhjBH5TGHEfyZeeew2HYvcjv4HLAznuFHsI/lVKzoED8p45PDRsUXjiTYDe9Cr7TlQQMxnlbhtRC5M2vK9IycQrvApcLARNzPFT830gqwHuc1WHqTqStdWCCU9XY7s7raeWcd1gRgz+bE1ErR6FBFxyP9UMjPMcJOPfkU3/fFqQPmIy43IZDduJUXmYaqFGy1wNgnlWG/4Bds7A5wuBt/wagE45jq1as5N1+4vsbTRELCKAu+X6mMgrTZN8gv5kyZ7XC/Rq1wt6y4j9La9zr+6aQU5uGnWLmLz3wZCBpVghq7k8+UzGiu6SPd29jOBOCpWa+SgLW5gU+0n5fLekcVTI3OjHr5icTGKHkEi+OtYueFchziFUmXSXEmO1VurNkY0pnVe89A1SOZ5dFeX4eIyJ6ZT32dxJbFhW/egxzQERtNTq5M3eF5H5RGnGLjv2ElgFyaMkBHq1mGp5UTNRbQArERb7TKF28JmLGmcCGkMtPn+tJKuuClRCX/OBIlk0gdU88n/3p6wMlyMVwKlmbv4fp
  template:
    metadata:
      name: headscale-oidc
      namespace: headscale
