---
headscale_version: v0.29.3
headscale_sha256: "8dc183758024ed7095cf610fedea0790233613c71353bc8be2715d82ba29b92c"
headscale_server_url: https://vpn.shychedelic.com
headscale_base_domain: ts.shychedelic.com
headscale_dns_nameservers:
  - "{{ pihole_dns_ip }}"
headscale_dns_search_domains:
  - "{{ homelab_domain }}"
