pault_gate_word: ENC[AES256_GCM,data:nrVkanEPlU8=,iv:ejdzWxr+CnB38FSjtKqvzV++kbPREEkUy1ETQVP71Q8=,tag:wn80wMFM12aHe7RJoFQgLg==,type:str]
pault_session_secret: ENC[AES256_GCM,data:2ZrU74z68TjAYjRTynEy67UV5J/RIKkzWXv5YEtIoPatxLgbkAC3awNORispj0iZMPy30jaC8SHN7CIDIyve8Q==,iv:iRdm6k4o7SJ2RMNrZ5sUS76577kCYt9wkedCRATsthc=,tag:tfJMVPa5zSirt23qUjcM8Q==,type:str]
pault_minio_root_user: ENC[AES256_GCM,data:iBGSEtu+AF9flg==,iv:djmiF6+/lZsxwZ0twHHRly3Ab7SpD+er2GRlJSoB8nw=,tag:JzDO6+6rNRT0e04IbXffeA==,type:str]
pault_minio_root_password: ENC[AES256_GCM,data:yeO4SFrMMfDaVOKhQE0cSW/yRh6QKEKHMyjs+WVXwgs=,iv:CH1E+M5tbxyMmfYzPoZdPBW1Dlm0x96rY1iS6Pg+LHE=,tag:tIIne+QpQ/0qZTynQDoHIA==,type:str]
pault_s3_access_key: ENC[AES256_GCM,data:01w5i9ciy7ir,iv:CdnWIvgzWCJVGf0J+fLMWW9dRkpkGnHD17aArb6FUX4=,tag:nuP1MZgAp30ZDgzOsg9f5w==,type:str]
pault_s3_secret_key: ENC[AES256_GCM,data:1UE0T2AHeP0vAqMAeD7xw7ESRIUrl5MpVKijT6yuK/GYHmk365nR3A==,iv:H3gpxF/btW2+TORNzGh7aoCMeGN/SAyFtJxZxppJTUA=,tag:DJEd1mv6eJlIBqGwpEdBeQ==,type:str]
pault_tunnel_credentials: ENC[AES256_GCM,data:AXECJ2+HxD3thp47K8VxnnnWu9StLEPJYj1lL/YTL/OSa2BI6kXHN3OdGh1Dq5Z8jORtSyEjWwjk+hSC4Jn7or9UFcPpDMrSUmDyJS4NK2Q12NkSPmKICbBLJJ1cGif3o34hVPq1yIidbKyK3njmLGYk7+kpeq/o9qSLGdXHDsWcopQ03Qx5uT+4NYWNh8EN8CT0XriiL34H7w8Lf306yUQBNP3q574AnDFub7Vw7g==,iv:FOHpe4x84qp3OWJEA1mibXAMLAAWHia4GFgzHPbLH/w=,tag:IaL9Ng94PoUp1RWUFMvTnA==,type:str]
pault_s3_readonly_access_key: ENC[AES256_GCM,data:eUyvPVuLTsg=,iv:Q2igyf35dLvAmpKBDmMq3vk67Yn9d8f4WnIHMZRS3m0=,tag:azOwbN4fhDwTJpA77+z/ZQ==,type:str]
pault_s3_readonly_secret_key: ENC[AES256_GCM,data:D1WOoM2vgw9X0SzmK/yGh8shd6p1ybWyV08cdE+Qoi6qyTSrSvFy+g==,iv:F2efWgYqorq9fHbgDf94vnwzhax1kj5vMV3SJIEGLfU=,tag:onVQiUo9Wo5/GKBWyIDmXg==,type:str]
postgresql_password: ENC[AES256_GCM,data:3Vab67EKQAS9H8blJVtO1QhCRTjTPDswCdGkXbODrsg=,iv:6AuCrLovr/t3S+WLyJLvueLMU3f8MqZuDV3R6yOOiis=,tag:Iy5VcgZZFzxfm1UnJ5ANHw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NlYrUnN1UnRELzZNV3Rq
            UWtTNjZKY0c0d2tYbURsdG1XQjJyeFlUckNBCmJ2NjlTYWNJQWkvWmZnaXRORmxM
            eUhnMGU1UHhYWjhuNnRrbUpHRisxWWsKLS0tIHpweUZzNW5Jb2JmK0x5UHJLNlRJ
            RWFmTEttbmsrcU8vcVZ5WmlPaXVmMzgKkheok1BNW81Bwnw2sENzukWyrQ7u+N1j
            NGJ3IJ3vZNwYx0txvk5e8gGF5SwcciHvTSrK1jzRqG3N3c1A4gYxmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gt9v3qjej3vuykjydqv9amhsjucanjwwtt4w8fkf5thyssrdeuus5ke3rx
    lastmodified: "2026-07-31T05:40:34Z"
    mac: ENC[AES256_GCM,data:4gzlpjJrpG98iks+W4YID9bOuaHvTF84wa3VhTjtk3kZzLhl+AYZQQrCRmW8S9i7YEYfx6MCuQNUHCZ7+Mul0+SKA7lVwH13X1RhCTjgqN00Ase0D2OAvU6iZYUmxK0Nl1slpoU4RPRTylihEn7jEcqmoa63MTG8fDgRXOBqo2E=,iv:xDfIWy/FlDeFimQpuUkMjYRgrec+upiPHV+zuHNw2mw=,tag:tmuNgoVyBXlJghQGXNOU4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
