pault_gate_word: ENC[AES256_GCM,data:xergcd0ZAJiHSZhlkbImWMuJYRUev/0NWqUtQ+WGivE=,iv:AFllaI3kjnTEXwa7hrXn7GHiSdXVxjkDZk2sBgugAvw=,tag:Rm4XzSdThl/sISrOPecKMw==,type:str]
pault_session_secret: ENC[AES256_GCM,data:RtGNDhNnYkzdE70N9kQpqZNHlUnZpJnKNpOp9fZmf/M=,iv:+G6BXdFuu20tU0U1qMDdzqjt52iY36eM1JSJ4gKUPFM=,tag:5L5oNuSPskIq1m7YIBx9kQ==,type:str]
pault_minio_root_user: ENC[AES256_GCM,data:HW0mzRRDknrsY9bz,iv:AuWBsSR0u8aoEDr2QbNaKmdm7BSNTztnv8409hQ9FX8=,tag:rKJaOF39GqQxWjxX1Ypy/A==,type:str]
pault_minio_root_password: ENC[AES256_GCM,data:emmqUowbm1foOSXUWPpk1qo8tcB7lu2TCyAWCsmyXsg=,iv:awDAQ7N+HfecermdTgEvurjUKm1J3FDBfPbWzRxvdSo=,tag:8s/Ful4f4Z4fBQENpIugZQ==,type:str]
pault_s3_access_key: ENC[AES256_GCM,data:F5rz+N28KrzXxn599KeuqQ==,iv:ZVuLtYW22jj4wsukAgJ7o3bbGnRuQ5Q1gzG9V5VIJT8=,tag:XYHCTYAHY3qU+0kgSkhAmw==,type:str]
pault_s3_secret_key: ENC[AES256_GCM,data:FTGh9vPsZ6dyr56Jr3BmL6i2heDxmZBsfxRbtTyY3vc=,iv:JdGanYrU51RfTg/S5u93siO4EAMvDJW+Tk1AN42H3w8=,tag:cbQg5QRuTJdgOMKRRVJ6mQ==,type:str]
pault_s3_readonly_access_key: ENC[AES256_GCM,data:3kT0khIp6F/l6yzVytpS+w==,iv:Xtbj0fofJJx8Mg3+U4iQLQY84YYkgCkInk6C3/7GCQM=,tag:CcePTiUTbuRO4qneZSXG4w==,type:str]
pault_s3_readonly_secret_key: ENC[AES256_GCM,data:RKOXiAl0wZ6cyl6o2l1QZ0fKVDjrRKEC/vEsV63V+Zfn6K1MPlBJww==,iv:5zVQTMN3eK4hIqrhdgfN1iOAVgD4y/ZQlVHFCYYpwSI=,tag:yJgYrY0JIhjbfa5e/BU24g==,type:str]
postgresql_password: ENC[AES256_GCM,data:q+bIhXT8eB0EA1UU0GyXdbM0hF+u/KAOKY181nLFcSM=,iv:HmqmBBUdXAi+4+flhylCB6+yOoNczFpFbXguaeMIfAM=,tag:dg55VJeZGyGh2kqJn4mRyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHanJnYnpTbWVLVkgxcmt2
            NFhabHZuSGxzNFhIT05kdjdyUkhqL1R6bFhVCm5GbWp5cjM2dlBSbnhtWHc4UmdG
            bEQ2VFV4d1VKSnUvekNuWVJ3WVJoTGMKLS0tIGZwL0xlZWR2Vmp4VVkxVHV4bVNV
            eVlhMnFjZlBMQ3lTUUxxVUF2WjYvdDAKzKmxjGk5hn0LpLjL+xi7ZavTFS4/BjWo
            2TQ6ooEPcGW317jws7fh8EAjJrY0hfqXmayHcKEVpgL3v4Yh2kSKZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gt9v3qjej3vuykjydqv9amhsjucanjwwtt4w8fkf5thyssrdeuus5ke3rx
    lastmodified: "2026-07-31T05:40:34Z"
    mac: ENC[AES256_GCM,data:WIIW/vdRUcdwT2nQqTWF1CsxNqOzmQhDnBinpiW1/t5thkzFHWN3uN0JI80qzKmlYruKJtNhuuOkLHJNy/OBlQ1W90dNW0OiyiPXBG8ytaGBbNyVoOn9fpwU21I5xJwrJ4e4Iym2Gz3KxlXAv9BkFNeeB+c2owewPJaismpLDys=,iv:HzITWtKhYNWuLEBjvs1Spz3AS9rs7sLEKKFapSnMQWY=,tag:U2/pc4xx6yAzDHTTmA4mxg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
