---
pault_container_id: 107

postgresql_db: pault
postgresql_user: pault

pault_minio_image: minio/minio:RELEASE.2025-09-07T16-13-09Z
pault_mc_image: minio/mc:RELEASE.2025-08-13T08-35-41Z

pault_public_host: pault-staging.lab.shychedelic.com
pault_media_host: pault-staging-media.lab.shychedelic.com

pault_web_image: git.lab.shychedelic.com/phillhood/pault-web:606da19a
pault_api_image: git.lab.shychedelic.com/phillhood/pault-api:606da19a
pault_tunnel_id: ""

pault_seed_target: true
