---
caddy_version: v2.11.4
caddy_sha256: "02d058c1bcd1d85700b953666dad2a28a99bc03224549ab952ef062a419ab8e4"
caddy_download_url: >-
  https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com/caddy-dns/cloudflare
caddy_acme_email: phill@phillhood.ca
forge_backend: 192.168.1.103:3000
registry_backend: 192.168.1.104:5000
pault_web_backend: 192.168.1.106:80
pault_api_backend: 192.168.1.106:8080
headscale_backend: 192.168.1.107:8080
headscale_public_host: vpn.shychedelic.com
