---
- name: Configure APT repositories
  ansible.builtin.import_tasks: repos.yaml
  tags: [repos, proxmox_host]

- name: Configure host DNS
  ansible.builtin.import_tasks: dns.yaml
  tags: [dns, proxmox_host]

- name: Configure root SSH keys
  ansible.builtin.import_tasks: ssh_keys.yaml
  tags: [ssh-keys, proxmox_host]

- name: Configure Terraform service account
  ansible.builtin.import_tasks: terraform_user.yaml
  tags: [terraform-user, proxmox_host]

- name: Reclaim thin-pool blocks
  ansible.builtin.import_tasks: fstrim.yaml
  tags: [fstrim, never]
