---
- name: Ensure root authorized_keys
  ansible.posix.authorized_key:
    user: root
    key: "{{ item }}"
    state: present
    exclusive: false
    follow: true
  loop: "{{ root_authorized_keys }}"
  loop_control:
    label: "{{ item.split()[1][:16] }}..."
