---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homarr-secrets
  namespace: web
spec:
  encryptedData:
    encryption-key: AgA+DyXcT4IzYiRk+vORvQORqHFqMECa9JbyEQki99WcKamvcP6+of++WxM6OfsSvRdWeBA3MYlro8Uglelj4HrcOImSYkXvKzPlzBvfXzFCC48vTOesF50iTZa0X0RrfwxiPEn40vULhPIpaeIGJZhMBVu7Vb+2RtXe2eAQDybNdCxRAZ3iPMXuF52QyB+gxZ7+dw3/3zqcdHApdPHHaUHtiHqgftm2POV0iZA35STGpT5lczLddF3hDqb7XgRWkv92Puu9+BMSMf0KqYakcZNqVzl8TDwyJrB5l3Er4BV6DQ1ED52kCzzSHbjIvqgyYSHaJXBDpTPf4YIlMF111c7AhdNhzlJq/UzgclugS+zWoRCFgkF0h71HahAOmeoI9whxQb4CJO03LVwNkOa6RFABpk3/ycBUX2HdKmduZh5fdp6TCf04UMUt2te9hPFZ3y2y8P9gmmEqjOkW2XqyX4qfUsolGL6ExxlOzcehaBNXLU1LLrBBzHYE4jFzpE88Z/lEAw4JtC+cYgqqnBgdy2MQvzgmF5QzhOPCrntGqkQLA/HnP2xHb4heTIIqJtr0U5g2DqW1n5tTIuhGj12AQUUYNurIn0W05EzrGHIKqMbLTVv5qgJwC1cfubZ5F7+ZE3YAbQQ3XAePqhM9XSTi6EZuMpWJ83q5Zelo6fBPzl8vRB6PA+AvIyaKukBBB7Ip7rUwC8EuGqdBkPs1A8dCnQuD8UjbzaxDDgp9Sns9z2in+1GnvCLIv9W9OvpXUvGC0q1QQUU9E/Amr/Ze3EByM8iW
  template:
    metadata:
      name: homarr-secrets
      namespace: web
    type: Opaque

