---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: databases
spec:
  encryptedData:
    postgres-password: AgBBFMsZ4uvMiRQt8CXwWELE6vNonKTXX9F6K7NojAV0NLDm51rAZMonMQ9qsRMYLKYNWU4QZkfZ3JvjXuBimJ+fjpP9euElemdZ06+3DkvWsDdKTZ1Kzi9wt1v1Mh2UBOEfZi5NarB1iL9GWFKrDAIwVAxXUX3vCKMm31TZW+WbClj3PNNhyl9NnpgB5QXWWziU23rmpfoftli/NgRyLhPWkpdI1R3/Dm378itWuM0fV1h9bt0WRNE5ffQPZZvcebOv1JiYffe2oPhn4DbZkmThfy1l/ACbYdg+ZnCqNAYX3MbgvKpVmdRMY/aGJ+GTibzdK+Ez5Lm3JtLs1UGloK1g9j86BokkPFqiTe1C3MMntmtS2QMfODn5xC7yG95mCBHpyR5VxyqkAA2po7G+EoF0JvZzKHxRYCUlK/MaaVdwWSX+J5A/HUeZnAG5//QDnJn7JereL7lYy1KG4KCn+cWAU1v0+7aE7e+UvC1C/Mkw0E5N+jGBnm5uSULZ32Z4LzykULkwwahXm2jNNN7DrRAaCG+17esmlnErVNIrRpvnpDo7bfGEvNS4Nk1JO/l//0n1qsmViwGqZXbiiGDIHmd2rIJyUzhjbaokayMRo4dH9CthWriL5ZQhYhQCS6HFyO/a9ex6kzcdlBBMsCsXdfFWEw7KEvAU9V2AEVf8+27V9eDoq47bb5K2axXnsN938z3hCa1Z9RDbdHwY+jW9
  template:
    metadata:
      name: postgres-secrets
      namespace: databases
