---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pgadmin-credentials
  namespace: tools
spec:
  encryptedData:
    email: AgDR45qkGJmW4MI+Tt/6E5WydBnIqZKFnbDJ9iDJz7AYU2MNYPA2wXtVhPbvxId1W01xXNCXbrWANBZzwo/Cun6Jov8iraYjYY5++zui8mNpxuRR2+gSVGaJ2My1ROAfWR70fupUvXZ0euILXJOzuxItJRm2QTFmRB0Zr1W/e38HfsShWhZCyaEfJEiwKFnYSdV8mOIi6NvaA2zl4KtaKT5IpBDdAkqC8aJyZEHeB3/iWmSGu3HWdwWf2ixLzP/InnU3pNVwpqsCM2Unutvl8rW496Ht0VDDoCs8lSEZlE0cgkHS21FcyEg0sJzDF4tRFJ51CPFPd6cBDwMTVsjxROOh80i5XXf0dFmDXz7quD7OZ+NsUlzWTHJX6R3hD4HhiDSXKxVEo3EEk5XM3k47VIgXuhRjR1kNAu/J62yOYys0VC7Pb4nkd5HXvI0u8wsj+zXMUoK2mYMQaB4pT8TuC3pHtn2zR2OmWvlbgLO3/3n/SAudBkKfv9hbFbLTvlFHFA2VGD2+u9XKlV27jxZv3WIA5+1EpX6MLp5M5kmpsAz5u32w6m08Vzn5f7Rb6nNltNgxtVLDDLeT83mv0p+Kz4bHVgDSxmaTxPEGNCG0QxsTMRKIDSIKufmuevieEbOGPu4WTRxDTKIN9ErXCNU02+ZxlBGbxMD/KQSihuLlGyyerNjtExkJm9kbpkocWcau9bL3WxJ8sk4JurmaAGBP73M=
    password: AgCc2TuBB5rz345eNKlGxv7ejh8q+GKRz+865JrhOmzC8a8nHDiTH9o+VM7pUARcHLun7a/xRhAoXLWuFDbqXrSC/r2aBQkFobs/unELpbOQYZ7IzcMHHK+GE/WuvKhrrdTkLdA40OhozriKvnxorGuPVSHC2QMsv/QJRTkaC2X20WIygH+vJxoZ2ikFIOhqSFZdMpSCDGU+tq4DKjvWH+zP3Bwy6LFd88qTQgxtmJD479lByQ3vbnqQf045EwAXN01a7omjyioPvOyXY4pIu7D8puRbV2SRtznwl1foEMtQN3S8cW0BjGgoj70OPORL+ETtXhNFEdcISRC9+Q/pxLyHhTK2RC2qNioNyijdWYILX4w3s/ahslW12dcU+4KALc/wDgm34o2yWFxzc7kgYd9y3EQRBatNHAaddpc2kH658vL19VYdvIqwuxrn0KRN6zYIxA3AnIeLhr+QHdRBnAj6VsGt2eM2UsadvaIJUhG3b1uXYENGktP/XzTAKIxQxMhbxgTE4Bi4072a1LoDd7HTculMcGZGplRIDtAjfB8kshQpsfa1MNGAxSeZii2u9Iq/phUP79XpM/vzR3RXEyADAhcVcAH4icK8L6IUOL1VVtu3Dp1o1bKXQgvSXoTuPNX77yU6OLdfiAbams374LGqzFV94hSieBLRn3JjaqSZjc0evAPBEkKocBfEtGUugFuUduVxiw==
  template:
    metadata:
      name: pgadmin-credentials
      namespace: tools
