---
apiVersion: v1
kind: Service
metadata:
  name: opnsense
  namespace: networking
spec:
  ports:
    - port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: opnsense
  namespace: networking
subsets:
  - addresses:
      - ip: 192.168.1.1
    ports:
      - port: 443
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: opnsense-transport
  namespace: networking
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: opnsense
  namespace: networking
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`opnsense.{{ .Values.global.homeDomain }}`)
      kind: Rule
      services:
        - name: opnsense
          port: 443
          scheme: https
          serversTransport: opnsense-transport
  tls: {}
