---
- name: Install Tailscale
  ansible.builtin.import_tasks: install.yaml
  tags: [install, tailscale_router]

- name: Register the node
  ansible.builtin.import_tasks: register.yaml
  tags: [register, tailscale_router]
