---
- name: Update the pveam template catalog
  ansible.builtin.command: pveam update
  changed_when: false
  check_mode: false

- name: List downloaded templates
  ansible.builtin.command: "pveam list {{ pve_iso_storage }}"
  register: pveam_list
  changed_when: false
  check_mode: false

- name: Download the Debian LXC template
  ansible.builtin.command: "pveam download {{ pve_iso_storage }} {{ lxc_template_name }}"
  when: lxc_template_name not in pveam_list.stdout
  changed_when: true
