{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scryer-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scryer-postgresql
  template:
    metadata:
      labels:
        app: scryer-postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scryer-secrets
                  key: DATABASE_PASSWORD
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: scryer-postgresql-data
---
apiVersion: v1
kind: Service
metadata:
  name: scryer-postgresql
spec:
  selector:
    app: scryer-postgresql
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scryer-postgresql-data
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
{{- end }}
