apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scryer-tls
spec:
  secretName: scryer-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - scryer.{{ .Values.global.hobbyDomain }}
