---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scryer-secrets
  namespace: gaming
spec:
  encryptedData:
    db-password: AgAxrY9R1H/BmZZDvO2IkkLb/H1R/J2ECXtQFH5Vzdtge00BnXSOOIK3+tqHrSxoHlK6T5576pivcKZ/Ls+EVn1+UdiP32W/EZjuit+hqX26rortBGwOH3UG3fLmpV80NPaSZP6iomDAuolSopIWIQoKyEVKzEkqi7UV5vzsNvHGjI/aoaDGXIkKq0ktPqjsjZnnppJX3uOHc/XfdYxo7bL9ErQAY7oMeur1Hc15517QhD24+K/HXQ2MbqAyNGCGLt8uzvbT7oFoLLuEovE32EBknVt0zgHCGPIrH3+sqskPZ7PfA/1OhgMHG/JGcKK0pJX0BRYF/PKrjmLnfFE0oNLRVwPr6IIuWcyWE2N9UXN59sbcnIcz19MHxdpegqmj8Eb5xug3KowxNy5JgODrpj7MV8PDMqpeYWJcTI+yTHaEekMPoEuQXsIe8/49S0xxlX7PQYuq38NV4kmnxaZk1YnVCdto0Xh6Sy69GSQWKSeZX8S6Vw+5hynS81KKfMDuskE+N+vivcL8r4Ijg+icufGfbGhDOFG4j1vPNJP6aAReVAqTAeBMq5PvX6sPuQiHY8ucwKjLekGgqJR5t/5EcF1mqNRtFuSk1Dcn/pJQtdOH0YYArYUxlXICFM/KgzithE9hpjLuRL0VthndRYEDhSbNEc+4jeoJRLaYIwDnCGjpO/9/BHQuCsyUQUa8bSjeykGemXnnVNgOggsRKAVVqO4C
  template:
    metadata:
      name: scryer-secrets
      namespace: gaming
    type: Opaque
