apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: scryer-secrets
spec:
  encryptedData:
    db-password: REPLACE_WITH_SEALED_VALUE
  template:
    metadata:
      name: scryer-secrets
    type: Opaque
