---
music_host_mount: /mnt/music
music_fs_label: music
music_fs_inode_ratio: 1048576
music_host_uid: 100000
music_host_gid: "{{ 100000 + music_gid | int }}"
music_container_id: 101
music_container_mount: /srv/music
music_container_features: nesting=1,keyctl=1
music_format_disk: false
