---
- name: Set the Pi-hole web password
  ansible.builtin.command:
    argv:
      - pihole
      - setpassword
      - "{{ pihole_web_password }}"
  when: pihole_fresh_install | bool or pihole_reset_password | bool
  changed_when: true
  no_log: true
