---
- name: Configure Proxmox VE hosts
  hosts: proxmox
  gather_facts: true
  roles:
    - proxmox_host
    - pve_templates

- name: Base config for Debian LXCs
  hosts: lxc
  gather_facts: true
  roles:
    - debian_lxc_base

- name: Configure Pi-hole
  hosts: pihole
  gather_facts: true
  roles:
    - pihole

- name: Import the music NAS plays
  ansible.builtin.import_playbook: music.yaml

- name: Import the tier0 plays
  ansible.builtin.import_playbook: tier0.yaml

- name: Import the pault plays
  ansible.builtin.import_playbook: pault.yaml
