---
- name: Configure Proxmox VE hosts
  hosts: proxmox
  gather_facts: true
  roles:
    - proxmox_host
    - pve_templates

- name: Base config for Debian LXCs
  hosts: lxc
  gather_facts: true
  roles:
    - debian_lxc_base

- name: Configure Pi-hole
  hosts: pihole
  gather_facts: true
  roles:
    - pihole

- name: Import the music NAS plays
  ansible.builtin.import_playbook: music.yaml

- name: Import the registry play
  ansible.builtin.import_playbook: registry.yaml

- name: Import the proxy play
  ansible.builtin.import_playbook: proxy.yaml

- name: Import the forge plays
  ansible.builtin.import_playbook: forge.yaml

- name: Import the pault plays
  ansible.builtin.import_playbook: pault.yaml

- name: Import the headscale play
  ansible.builtin.import_playbook: headscale.yaml
