---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mas-config
  namespace: comms
data:
  config.yaml: |
    http:
      public_base: https://mas.{{ .Values.global.hobbyDomain }}/
      issuer: https://{{ .Values.global.hobbyDomain }}/
      listeners:
        - name: web
          resources:
            - name: discovery
            - name: human
            - name: oauth
            - name: compat
            - name: graphql
            - name: assets
            - name: health
          binds:
            - address: "[::]:8080"

    database:
      uri: postgresql://mas:__DB_PASSWORD__@postgres.databases.svc.cluster.local/mas

    matrix:
      homeserver: {{ .Values.global.hobbyDomain }}
      secret: "__MAS_SECRET__"
      endpoint: "http://synapse.comms.svc.cluster.local:8008"

    clients:
      - client_id: 01KHHNN52NQBZE24GERS5SZ4PK
        client_auth_method: none
        redirect_uris:
          - https://element.{{ .Values.global.hobbyDomain }}/

    upstream_oauth2:
      providers:
        - id: 01KHHK7SVXN49CMHT6HGP4ZVGB
          human_name: Shychedelic
          issuer: "https://{{ .Values.global.hobbyDomain }}"
          discovery_mode: disabled
          authorization_endpoint: "https://api.{{ .Values.global.hobbyDomain }}/oidc/authorize"
          token_endpoint: "https://api.{{ .Values.global.hobbyDomain }}/oidc/token"
          jwks_uri: "https://api.{{ .Values.global.hobbyDomain }}/oidc/jwks"
          userinfo_endpoint: "https://api.{{ .Values.global.hobbyDomain }}/oidc/userinfo"
          client_id: "mas"
          client_secret: "__OIDC_CLIENT_SECRET__"
          token_endpoint_auth_method: client_secret_post
          scope: "openid profile email"
          synapse_idp_id: "oidc-shychedelic"
          claims_imports:
            localpart:
              action: require
              template: "{{ "{{" }} user.preferred_username | lower {{ "}}" }}"
            displayname:
              action: suggest
              template: "{{ "{{" }} user.name {{ "}}" }}"
            email:
              action: suggest
              template: "{{ "{{" }} user.email {{ "}}" }}"

    passwords:
      enabled: true
      schemes:
        - version: 1
          algorithm: bcrypt

    branding:
      service_name: Shychedelic

    secrets:
      encryption: "__ENCRYPTION_SECRET__"
      keys:
        - kid: "mas1"
          key_file: /secrets/signing-key
