---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mas
  namespace: comms
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mas.{{ .Values.global.hobbyDomain }}`)
      kind: Rule
      services:
        - name: mas
          port: 8080
  tls:
    secretName: hobby-wildcard-tls
