---
apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-config
  namespace: communication
data:
  homeserver.yaml: |
    server_name: "{{ .Values.global.hobbyDomain }}"
    public_baseurl: "https://matrix.{{ .Values.global.hobbyDomain }}/"
    pid_file: /data/homeserver.pid

    listeners:
      - port: 8008
        tls: false
        type: http
        x_forwarded: true
        resources:
          - names: [client, federation]
            compress: false

    database:
      name: psycopg2
      args:
        host: postgres.databases.svc.cluster.local
        database: synapse
        user: synapse
        password: __DB_PASSWORD__
        cp_min: 5
        cp_max: 10

    log_config: "/config/log.config"
    media_store_path: /media

    enable_registration: false
    registration_requires_token: true

    enable_metrics: true
    report_stats: false

    signing_key_path: "/data/signing.key"

    trusted_key_servers:
      - server_name: "matrix.org"

    macaroon_secret_key_path: "/secrets/macaroon-secret-key"
    form_secret_path: "/secrets/form-secret"
    registration_shared_secret_path: "/secrets/registration-shared-secret"

    login_via_existing_session:
      enabled: true
      token_timeout: "2m"

    suppress_key_server_warning: true

    experimental_features:
      msc4222_enabled: false

    app_service_config_files:
      - /bridges/discord-registration.yaml

  log.config: |
    version: 1
    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
    loggers:
      synapse.storage.SQL:
        level: WARNING
    root:
      level: INFO
      handlers: [console]
    disable_existing_loggers: false
