---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-secrets
  namespace: home
spec:
  encryptedData:
    db-password: AgDFQq1lnJR6WGNMDCBflUrUZIjiZa6zk2M8WNY60Ufo79gb/33l3ch1v95Q3L6/K7R0HR4OpwYB/F9jaqBdtNJFwcbs86gYS46iX9ui79r16kwkKHOOawtdoSEdAmfYl7vv//EocWV8iscBOXWKx3uGLccbcTj/hJouzufoGMLayvA4ROG0a7WbfazbO/atQsu7U9qehkKyxfoqPw3YtihSYNjEhEKGMKtJmCadhSFWWwkBBh8HBe6oZ8o1KYkq8cQmo4mdSUyJvNTvY53BiowquyW7geTjTdelX/PQZiHs5RT2obsbOg+T6f6yWUNOyTSQ8KYvmA82y4FvbTxgOqFvEqIV2sP7jW28HhccmLqZPrPy1HQUnE6hM1ZSNPgYZfGaZu7GrC90idFmFjJS22DvHZB2Jt7DUWVzT6v97s2owmwbWsjvTkQJYYf1QtFeZztq6u542MuFHB3LQPYKLpi4O161BfuzgMEeb/wSEKF+NPwfX2WLiuQZT6MRIFP2GuMFVEYN/Xwco2m4rtkU7BcEFPc7iMgAALGDThv866cLwkYzwuU3MCLMnoB1Lx8hDkkGtV5T/caiMeKq/RHRwVu6S567jf6WMsFtaY6YXMNaEj05MpdfkGiPAovq9KqPn+rXnfBK0Qsa0LYQJfiKbUX0OPg3hfZQVJfsz6epeiVg281onAdGYRiOMMlU7sp2jNZbsukr1+BobxC4beLBC9m/n+0MRTYc6Z+ODjSqMzHjhQ==
  template:
    metadata:
      name: mealie-secrets
      namespace: home
    type: Opaque
