apiVersion: v2
name: headlamp
description: Headlamp Kubernetes Dashboard
type: application
version: 1.0.0
dependencies:
  - name: headlamp
    version: "0.*"
    repository: "https://kubernetes-sigs.github.io/headlamp/"
