---
- name: Install base packages
  ansible.builtin.import_tasks: packages.yaml
  tags: [packages, debian_lxc_base]

- name: Upgrade all packages
  ansible.builtin.import_tasks: upgrade.yaml
  tags: [upgrade, never]

- name: Set timezone
  ansible.builtin.import_tasks: timezone.yaml
  tags: [timezone, debian_lxc_base]

- name: Verify container health
  ansible.builtin.import_tasks: health.yaml
  tags: [health, debian_lxc_base]
