apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.pharah.ca`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: home-root-wildcard-tls
