---
- name: Install Forgejo
  ansible.builtin.import_tasks: install.yaml
  tags: [install, forgejo]

- name: Install the custom themes
  ansible.builtin.import_tasks: theme.yaml
  when: forgejo_custom_themes | length > 0
  tags: [theme, forgejo]

- name: Configure Forgejo
  ansible.builtin.import_tasks: config.yaml
  tags: [config, forgejo]

- name: Ensure the admin account exists
  ansible.builtin.import_tasks: admin.yaml
  tags: [admin, forgejo]
