---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cinny-config
  namespace: comms
data:
  config.json: |
    {
      "defaultHomeserver": 0,
      "homeserverList": [
        "{{ .Values.global.hobbyDomain }}"
      ],
      "allowCustomHomeservers": true
    }
