---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-livekit-jwt
  namespace: comms
spec:
  stripPrefix:
    prefixes:
      - /livekit/jwt
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-livekit-sfu
  namespace: comms
spec:
  stripPrefix:
    prefixes:
      - /livekit/sfu
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: livekit
  namespace: comms
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rtc.{{ .Values.global.hobbyDomain }}`) && PathPrefix(`/livekit/jwt`)
      kind: Rule
      middlewares:
        - name: strip-livekit-jwt
      services:
        - name: lk-jwt-service
          port: 8080
    - match: Host(`rtc.{{ .Values.global.hobbyDomain }}`) && PathPrefix(`/livekit/sfu`)
      kind: Rule
      middlewares:
        - name: strip-livekit-sfu
      services:
        - name: livekit-sfu-ws
          port: 7880
  tls:
    secretName: hobby-wildcard-tls
