---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zilean
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zilean
  template:
    metadata:
      labels:
        app: zilean
    spec:
      containers:
        - name: zilean
          image: docker.io/ipromknight/zilean:latest
          ports:
            - containerPort: 8181
          env:
            - name: Zilean__Database__ConnectionString
              value: "Host=postgres.databases.svc.cluster.local;Port=5432;Database=zilean;Username=zilean;Password=zilean"
            - name: Zilean__Dmm__EnableScraping
              value: "true"
            - name: Zilean__Dmm__EnableEndpoint
              value: "true"
            - name: Zilean__Dmm__ScrapeSchedule
              value: "0 4 * * *"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: zilean
  namespace: media
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8181
  selector:
    app: zilean
