---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: shychedelic-api-secrets
  namespace: web
spec:
  encryptedData:
    db-password: AgAq1y91mbQcHMKC33tdhXMLoE9/8iIhU1wYr7V0yMQyUNDHSJ5SvKFnslWQBpp7kaBuVZo8BZrupZz4t+HCw81bp32x//iXiodq1hTHo1v+frXOqYpzWB5bbaaUUqUdVoUBZITHKGN9U+PCS3ZpaLxbCP9FZUEPt3hK26BbKyyztbC2cBn7287Vvnt4ezQUZ6dbT1Ybm1mqG5vwBydLS9fW4EZrmtA3fGQOWct5YhF37HIjHNaZahEcV67tbsGhQM3aIBBBWWPGid7jANsAHMzOxIsKYpenPtmDk+TFQwUVONdTvcCpmogOUKk63Ls9AKDVC6pr5iV2O8Ln/ZK5LyRrWVVod9fUi6g3zjLChvwGsqqH4/1mAF936ieVL4n9j6oDiVuGgsgGmuL7xZ4J73VCk5xjqjCAhhvmI7c5M2I7w+yoeUMiQ2TnAq+2TubkbKH5gBStHcULfjX4be6zH5Kl4j8I/vv2wk+gSchvkB+GKgwtGrcZUegdd3pugcc60Dsd57Ho7Pn6tJy5gnysx20gD0L8hxHlREq12Iec4mTtfhWPGKkEM4Y5IgzeM8Qoao483SuwUkrbjY7TVgcT4vRUaao6zAVW2FBk0quSuR1XiajI9Si34IfVl5lR5G6y58oL/vy/QP5clo91sJaKTyM7D6jyeaKf6z8O5yKZwiTF/bpTGPW0JH6IZCUivs6xdYPtKt0Nxhmf8ENBbxKbWf/tGui/w0Y0ZWXCCd8MZn1Ycg==
  template:
    metadata:
      name: shychedelic-api-secrets
      namespace: web
    type: Opaque
