---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgB0ezbVSAIAFTS6rkkqwvvtXLtZTHCWRTwwEaEyWUnYm6G/vahLsNCSzd5QqDBshZuJMc37c0SkDbre3vYz3hDBF5zWq8oPStYUwUt8g3nK/DWmUwKHzppiQtg7eOu78MmtfnC9oLvApPxyj3+Nurh9giGKulkRfy2j3tScchG3hT8r/coZMZ17w1yhle4eor4UxypgoKw8+SswhRMy9X4ZzmVGMulrtfTOEaJ6KCEuWQBcybggJpRelaEDuoTwy4r12i/Ir/ASWO8IkNGUI8FGMCnu+iMMzK8mH/UWao0OBxGxHYbJVWVcihVDdN1wfGG92jiV91kMW+CTaeqKj+k/MIhgQjAgSJVtrUOySL/jn9C7pDtZw2shF5XHJGwCbA3i1dx3PH7ZHrAUOA1I11Zgm9SjYPtJtyl1Z+o30PkPlD1DrGd2+frVVdDIs+IFTz4xSR5SIYxkpup9Qk/l1Q5OpzUp1Gxgcvo1m0RHcx/YoFpQpiDrsyuJdW8QVk8pcwSjCw6uQDY1Bk6GNj+rB/bMgGBm2YQxtz4MS9QdPaNAdOOQPKQl1FWHDQszalL5zgFrKFNTny2FMlbDHTklXXD4hK16G3XXRz5IaDcTRyiNBeV/puLIxNqI5Kj68SH9mAln+hz+3bIUQaEH07laGjF9Pja/QgcWH7S90PjnWcKarKdh5BnOG3WWyXaYa/1vlBIGqTBgHdpLaxPMQdAoOcjO0QGO/zm9KLDE0lIaEP/8Yscq7JRG8gnqVZoGCEZqTilc7LiTcNMnArSz1a8QKBNzLzdaWNU9U50t49mKkcH9SnFMNzcgK4RKOD85RKQlDkqyrc876ERzQwtbrq+2hS0S4biRjgs19alIko52vnZ8BbqrKFUg16LZFfXtIGzlBZ5RJgOo4DyZifNSEXUnE71R6uDSIlOrKynglGK3tpUHlWJ5euN/PHuy
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare
