---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zilean-secrets
  namespace: media
spec:
  encryptedData:
    db-password: AgBajlSoO+4xBUOrOY4q9J2E2F33wwg0uBQpf9YxWDw5kOOPiH7EtFo0K6zI+98BeZe4j35sPXJ6FK/02zfjAscZyiutVomHeHvC2VWhjFGuf6023H6477MMIjic9UERlzmtihY40CBOI/KGPd/Fyc8PCRYvzGwRSeIroNxE/XoEO+HPD5grJFkmWqu+OMDGFJ2zvkFjGkWoiSs7XYEMdlw3JCDEjZvHuRU1crbI2sCKrZSpc9L6vQDpJuexzI4O5XavYad7eJhdvW85G6GGxL7dbxNWV82uwB8MIF6j+4tEGnxYh+KPP+jbmxoPsrUWvak5iparKglTX39IpKV17X3onMMT0eKKEPETIZWElzwuQU19hNrB/5eYx40DG3hHLG2Kr3GPb3NOCeJOhyb0S+sGXlhH12W4/LY+teaRpKXHMc+SmMMwiU8YxZbcB4/Y2FpZCvHE8yZ8+ZG6/QLo4XHQsTWGK2PbBz7ohv0OrM+B6GXb2z/UGUKq4E13/iCmYchQMq4CVDnZXN40hrK4v9xnu841FC7sZXz/5zXM3d8BnDTq7d7hTMBxx8+mEmMVPyYIhuo6jVMheVe3+srSDXvTw0DpgIoHn6PGFYCGWZ940sVjSkOTl/pyZMniEaerLU+kpiu9BMrREam+IPQs/7aVdLt3dPd6D+ve+HnwzUzt0eRJyb6+p4e6XjnaDETQVjzgCFPD3rnnOgpuxa9LWIM58gqt24tSFISroEyjLwbNJw==
  template:
    metadata:
      name: zilean-secrets
      namespace: media
    type: Opaque
