---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stickerpicker
  namespace: comms
  labels:
    app: stickerpicker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stickerpicker
  template:
    metadata:
      labels:
        app: stickerpicker
    spec:
      containers:
        - name: stickerpicker
          image: registry.pharah.ca/stickerpicker:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: stickerpicker
  namespace: comms
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: stickerpicker
